#!/bin/bash
set -x # echo on

# echo "DEFAULT, QUERY, CONTEXT"

python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 2 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 13 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 20 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 45 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 78 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:1/

python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --query --seed 2 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --query --seed 13 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --query --seed 20 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --query --seed 45 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --query --seed 78 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:1/

python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --context --seed 2 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --context --seed 13 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --context --seed 20 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --context --seed 45 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --context --seed 78 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:78_multigpu\:True_labels\:ds_frac\:1/

python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 2 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 13 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 20 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 45 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 78 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:1/

python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --query --seed 2 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --query --seed 13 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --query --seed 20 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --query --seed 45 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --query --seed 78 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:True_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:1/

python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --context --seed 2 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --context --seed 13 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --context --seed 20 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --context --seed 45 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --context --seed 78 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:True_seed\:78_multigpu\:True_labels\:ds_frac\:1/

# echo "NO FINETUNING"
#
python Advice_Classification_Simple.py --test --noft --data askparents --model bert --multigpu --seed 2 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --noft --data askparents --model bert --multigpu --seed 13 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --noft --data askparents --model bert --multigpu --seed 20 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --noft --data askparents --model bert --multigpu --seed 45 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --noft --data askparents --model bert --multigpu --seed 78 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:1/

python Advice_Classification_Simple.py --test --noft --data needadvice --model bert --multigpu --seed 2 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --noft --data needadvice --model bert --multigpu --seed 13 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --noft --data needadvice --model bert --multigpu --seed 20 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --noft --data needadvice --model bert --multigpu --seed 45 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --noft --data needadvice --model bert --multigpu --seed 78 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:False_query\:False_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:1/

# echo "TRANSFER"
#
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 2 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 13 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 20 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 45 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 78 --savedmodel ../saved_pretrained/classifier_needadvice_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:1/

python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 2 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 13 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 20 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 45 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:1/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 78 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:1/

python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 2 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:0.71/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 13 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:0.71/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 20 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:0.71/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 45 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:0.71/
python Advice_Classification_Simple.py --test --data askparents --model bert --multigpu --seed 78 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:0.71/

python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 2 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:2_multigpu\:True_labels\:ds_frac\:0.71/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 13 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:13_multigpu\:True_labels\:ds_frac\:0.71/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 20 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:20_multigpu\:True_labels\:ds_frac\:0.71/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 45 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:45_multigpu\:True_labels\:ds_frac\:0.71/
python Advice_Classification_Simple.py --test --data needadvice --model bert --multigpu --seed 78 --savedmodel ../saved_pretrained/classifier_askparents_bert_dropout\:0.1_lr_tr\:1e-05_lr_cl\:1e-05_wd\:0_batch\:32_finetune\:True_query\:False_context\:False_seed\:78_multigpu\:True_labels\:ds_frac\:0.71/